env:
  browser: true
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:  
  '@typescript-eslint/consistent-type-imports':  
    - 'error'  
    - prefer: 'type-imports'
ignorePatterns: ["styles.css"]